import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "../styles/globals.css";
import TourNavBar from "@/components/TourNavBar";
import {TourFooter} from "@/components/TourFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <title>My App</title>
      </head>
      <body className={inter.className}>
        {/*<ThemeModeScript />*/}
        <header>
          <TourNavBar/>
        </header>
        {/*<main className="flex items-center justify-center h-screen">*/}
        <main className="">
        {/*<main className="">*/}
          {children}
        </main>
        {/*<hr/>*/}
        {/*<TourFooter/>*/}
      </body>
      </html>
  );
}

